In [13]:
%cd /content/drive/MyDrive/Learn_Colabotary/Learn-Colab

/content/drive/MyDrive/Learn_Colabotary/Learn-Colab


In [ ]:
!git add Librarypractice.ipynb
!git commit -m 넘파이-판다스-연습

[main eeef60e] 넘파이-판다스-연습
 1 file changed, 1 insertion(+), 1 deletion(-)


In [ ]:
!git push origin main

Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 2.49 KiB | 319.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 1 local object.
To https://github.com/dding8838/Learn-Colab.git
   c925144..eeef60e  main -> main


In [2]:
import numpy as np

In [ ]:
A = np.array([[1, 2],
              [3, 4]])   # shape (2,2)

x = np.array([5, 6])     # shape (2,)
y = A.dot(x)             # 또는 A @ x
print(y)                 # [1*5+2*6, 3*5+4*6] -> [17, 39]

# 전치와 형태 확인
print(A.shape, x.shape, A.T.shape)


[17 39]
(2, 2) (2,) (2, 2)


In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])   # shape (2,3)
b = np.array([10,20,30]) # shape (3,)
print(A + b)              # b가 각 행에 더해짐 -> shape (2,3)


[[11 22 33]
 [14 25 36]]


In [ ]:
c = np.array([100,200])   # shape (2,)
# 만약 열(각 행에 다른 값)로 더하고 싶다면 reshape:
c_col = c.reshape(2,1)    # shape (2,1)
# 이제 c_col이 각 열에 브로드캐스트됨
print(A + c_col)          # shape (2,3)


[[101 102 103]
 [204 205 206]]


In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
b = np.array([[1,2],
              [3,4],
              [5,6]])
c = a.dot(b)
print(c)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]]


In [ ]:
x = np.array([[1,2,3],
              [4,5,6]])
w = np.array([1,2,3])

b = 3

#브로드케스트 방식
y = x*w+b

print(y)

#점곱 방식
y = x.dot(w) + b

print(y)


[[ 4  7 12]
 [ 7 13 21]]
[17 35]


In [ ]:
#퍼셉트론 계산해보기

import numpy as np

def step(z):
  return np.where(z >= 0,1,0)

def forward(x,w,b):
  z = x.dot(w) + b
  y = step(z)
  return y

# 입력 2개, 4개 샘플 (AND 게이트)
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

w = np.array([1,1])
b = -1.5

y = forward(X,w,b)

# 정답
y_true = np.array([0,0,0,1])
print(y)
print(y_true)


[0 0 0 1]
[0 0 0 1]


In [12]:
#다층 퍼셉트론 계산 XOR

X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])


W1 = np.array([[1.0, 1.0],
               [1.0, 1.0]])   # shape (2, 2)
b1 = np.array([-0.5, -1.5])   # shape (2,)

W2 = np.array([[1.0],
               [-1.0]])       # shape (2, 1)
b2 = np.array([0.0])          # shape (1,)



def linear_forward(x,w,b):
  z = x.dot(w) + b
  return z

def sigmoid(z):
  return 1 / (1 + np.exp(-z))

def forward_layer(x,w,b):
  z = linear_forward(x,w,b)
  h = sigmoid(z)
  return h

def activation(y):
  return np.where(y >= 0.55,0,1)

h1 = forward_layer(X,W1,b1)
y = forward_layer(h1,W2,b2)
end = activation(y)
print(h1)
print(y)
print(end)

[[0.37754067 0.18242552]
 [0.62245933 0.37754067]
 [0.62245933 0.37754067]
 [0.81757448 0.62245933]]
[[0.54862462]
 [0.56092542]
 [0.56092542]
 [0.54862462]]
[[1]
 [0]
 [0]
 [1]]
